ActionZoneRectHistory:
  type: entity
  table: action_zone_rect_history
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    subscriberId:
      type: bigint
      nullable: true
      column: subscriber_id
    organizationId:
      type: bigint
      nullable: true
      column: organization_id
    lat1:
      type: decimal
      nullable: true
    lon1:
      type: decimal
      nullable: true
    lat2:
      type: decimal
      nullable: true
    lon2:
      type: decimal
      nullable: true
    boundary:
      type: string
      length: 20
      fixed: false
      nullable: true
    name:
      type: string
      length: 100
      fixed: false
      nullable: true
    description:
      type: text
      nullable: true
    xid:
      type: bigint
      nullable: false
    isDeleted:
      type: boolean
      nullable: true
      column: is_deleted
    timestamp:
      type: bigint
      nullable: true
    accessListId:
      type: bigint
      nullable: true
      column: access_list_id
  lifecycleCallbacks: {  }
