ActionAuxOutputHistory:
  type: entity
  table: action_aux_output_history
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    subscriberId:
      type: bigint
      nullable: true
      column: subscriber_id
    organizationId:
      type: bigint
      nullable: true
      column: organization_id
    name:
      type: string
      length: 100
      fixed: false
      nullable: true
    description:
      type: text
      nullable: true
    outputNumber:
      type: integer
      unsigned: false
      nullable: true
      column: output_number
    type:
      type: string
      length: 20
      fixed: false
      nullable: true
    pulseDuration:
      type: integer
      unsigned: false
      nullable: true
      column: pulse_duration
    toggleOn:
      type: boolean
      nullable: true
      column: toggle_on
    xid:
      type: bigint
      nullable: false
    isDeleted:
      type: boolean
      nullable: true
      column: is_deleted
    timestamp:
      type: bigint
      nullable: true
    accessListId:
      type: bigint
      nullable: true
      column: access_list_id
    isTriggerConfig:
      type: boolean
      nullable: true
      column: is_trigger_config
    validityDuration:
      type: integer
      unsigned: false
      nullable: true
      column: validity_duration
    validityUnits:
      type: string
      length: 10
      fixed: false
      nullable: true
      column: validity_units
    pulseLabel:
      type: string
      length: 25
      fixed: false
      nullable: true
      column: pulse_label
    toggleOnLabel:
      type: string
      length: 25
      fixed: false
      nullable: true
      column: toggle_on_label
    toggleOffLabel:
      type: string
      length: 25
      fixed: false
      nullable: true
      column: toggle_off_label
  lifecycleCallbacks: {  }
