ActionZonePolygonVertexHistory:
  type: entity
  table: action_zone_polygon_vertex_history
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    actionZonePolygonId:
      type: bigint
      nullable: false
      column: action_zone_polygon_id
    vertexId:
      type: smallint
      nullable: true
      column: vertex_id
    lon:
      type: decimal
      nullable: true
    lat:
      type: decimal
      nullable: true
    xid:
      type: bigint
      nullable: false
    isDeleted:
      type: boolean
      nullable: true
      column: is_deleted
    timestamp:
      type: bigint
      nullable: true
    accessListId:
      type: bigint
      nullable: true
      column: access_list_id
  lifecycleCallbacks: {  }
