BeaconAudit:
  type: entity
  table: beacon_audit
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    beaconId:
      type: bigint
      nullable: true
      column: beacon_id
    oldRegSubId:
      type: bigint
      nullable: true
      column: old_reg_sub_id
    oldRegOrgId:
      type: bigint
      nullable: true
      column: old_reg_org_id
    oldAssetId:
      type: bigint
      nullable: true
      column: old_asset_id
    oldDepId:
      type: bigint
      nullable: true
      column: old_dep_id
    regDate:
      type: bigint
      nullable: true
      column: reg_date
    unregDate:
      type: bigint
      nullable: true
      column: unreg_date
    oldName:
      type: string
      length: 100
      fixed: false
      nullable: true
      column: old_name
  lifecycleCallbacks: {  }
