BeaconReprogram:
  type: entity
  table: beacon_reprogram
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    beaconId:
      type: bigint
      nullable: false
      column: beacon_id
    type:
      type: string
      length: 30
      fixed: false
      nullable: true
    timestamp:
      type: bigint
      nullable: true
  lifecycleCallbacks: {  }
