BeaconmodelPlanHistory:
  type: entity
  table: beaconmodel_plan_history
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    beaconmodelId:
      type: bigint
      nullable: true
      column: beaconmodel_id
    planId:
      type: bigint
      nullable: true
      column: plan_id
    xid:
      type: bigint
      nullable: false
    isDeleted:
      type: boolean
      nullable: true
      column: is_deleted
    timestamp:
      type: bigint
      nullable: true
    accessListId:
      type: bigint
      nullable: true
      column: access_list_id
    slTrackingInterval:
      type: smallint
      nullable: true
      column: sl_tracking_interval
  lifecycleCallbacks: {  }
