Blackberry:
  type: entity
  table: blackberry
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    phoneNumber:
      type: string
      length: 20
      fixed: false
      nullable: true
      column: phone_number
    haGpsDestId:
      type: integer
      unsigned: false
      nullable: true
      column: ha_gps_dest_id
    isUserplane:
      type: smallint
      nullable: true
      column: is_userplane
    isControlplane:
      type: smallint
      nullable: true
      column: is_controlplane
    msid:
      type: string
      length: 25
      fixed: false
      nullable: true
    pin:
      type: string
      length: 100
      fixed: false
      nullable: true
  oneToOne:
    beacon:
      targetEntity: Beacon
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        beacon_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
