CustomerPlanHistory:
  type: entity
  table: customer_plan_history
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    customerId:
      type: bigint
      nullable: false
      column: customer_id
    planId:
      type: bigint
      nullable: false
      column: plan_id
    xid:
      type: bigint
      nullable: false
    isDeleted:
      type: boolean
      nullable: true
      column: is_deleted
    timestamp:
      type: bigint
      nullable: true
    accessListId:
      type: bigint
      nullable: true
      column: access_list_id
  lifecycleCallbacks: {  }
