DepartmentDependent:
  type: entity
  table: department_dependent
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    isSharable:
      type: boolean
      nullable: false
      column: is_sharable
    introTs:
      type: bigint
      nullable: false
      column: intro_ts
    retireTs:
      type: bigint
      nullable: false
      column: retire_ts
  oneToOne:
    dependent:
      targetEntity: Dependent
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        dependent_id:
          referencedColumnName: id
      orphanRemoval: false
    department:
      targetEntity: Department
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        department_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
