Department:
  type: entity
  table: department
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    name:
      type: string
      length: 50
      fixed: false
      nullable: false
    description:
      type: string
      length: 100
      fixed: false
      nullable: true
    isDefault:
      type: boolean
      nullable: false
      column: is_default
    introTs:
      type: bigint
      nullable: false
      column: intro_ts
    retireTs:
      type: bigint
      nullable: false
      column: retire_ts
  oneToOne:
    organization:
      targetEntity: Organization
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        organization_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
