DepartmentItemgrpHistory:
  type: entity
  table: department_itemgrp_history
  fields:
    departmentId:
      id: true
      type: bigint
      nullable: false
      column: department_id
    itemGroupingId:
      id: true
      type: bigint
      nullable: false
      column: item_grouping_id
    retireTs:
      id: true
      type: bigint
      nullable: false
      column: retire_ts
    id:
      type: bigint
      nullable: false
    isSharable:
      type: boolean
      nullable: false
      column: is_sharable
    introTs:
      type: bigint
      nullable: false
      column: intro_ts
  lifecycleCallbacks: {  }
