EmailHistory:
  type: entity
  table: email_history
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    subscriberId:
      type: bigint
      nullable: true
      column: subscriber_id
    guardianId:
      type: bigint
      nullable: true
      column: guardian_id
    organizationId:
      type: bigint
      nullable: true
      column: organization_id
    email:
      type: string
      length: 255
      fixed: false
      nullable: true
    type:
      type: string
      length: 20
      fixed: false
      nullable: true
    priority:
      type: integer
      unsigned: false
      nullable: true
    xid:
      type: bigint
      nullable: false
    isDeleted:
      type: boolean
      nullable: true
      column: is_deleted
    timestamp:
      type: bigint
      nullable: true
    accessListId:
      type: bigint
      nullable: true
      column: access_list_id
  lifecycleCallbacks: {  }
