EventTtTrack:
  type: entity
  table: event_tt_track
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    beaconId:
      type: bigint
      nullable: false
      column: beacon_id
    locateId:
      type: bigint
      nullable: false
      column: locate_id
    networkTimestamp:
      type: bigint
      nullable: true
      column: network_timestamp
    lon:
      type: decimal
      nullable: true
    lat:
      type: decimal
      nullable: true
    triggerType:
      type: integer
      unsigned: false
      nullable: true
      column: trigger_type
    batteryLevel:
      type: integer
      unsigned: false
      nullable: true
      column: battery_level
    isBatteryChanged:
      type: boolean
      nullable: true
      column: is_battery_changed
    gpsStatus:
      type: integer
      unsigned: false
      nullable: true
      column: gps_status
    gsmStatus:
      type: integer
      unsigned: false
      nullable: true
      column: gsm_status
    hpaStatus:
      type: integer
      unsigned: false
      nullable: true
      column: hpa_status
    mpaStatus:
      type: integer
      unsigned: false
      nullable: true
      column: mpa_status
    lpaStatus:
      type: integer
      unsigned: false
      nullable: true
      column: lpa_status
    powerStatus:
      type: integer
      unsigned: false
      nullable: true
      column: power_status
    positionAge:
      type: integer
      unsigned: false
      nullable: true
      column: position_age
    senId:
      type: bigint
      nullable: true
      column: sen_id
    scenarioName:
      type: string
      length: 100
      fixed: false
      nullable: true
      column: scenario_name
  lifecycleCallbacks: {  }
