EventSleepstate:
  type: entity
  table: event_sleepstate
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    beaconId:
      type: bigint
      nullable: true
      column: beacon_id
    locateId:
      type: bigint
      nullable: true
      column: locate_id
    isAsleep:
      type: boolean
      nullable: true
      column: is_asleep
    networkTimestamp:
      type: bigint
      nullable: true
      column: network_timestamp
    lon:
      type: decimal
      nullable: true
    lat:
      type: decimal
      nullable: true
    senId:
      type: bigint
      nullable: true
      column: sen_id
    scenarioName:
      type: string
      length: 50
      fixed: false
      nullable: true
      column: scenario_name
  lifecycleCallbacks: {  }
