EventCheckinBb:
  type: entity
  table: event_checkin_bb
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    beaconId:
      type: bigint
      nullable: false
      column: beacon_id
    locateId:
      type: bigint
      nullable: false
      column: locate_id
    duration:
      type: bigint
      nullable: false
    isCheckin:
      type: boolean
      nullable: true
      column: is_checkin
    networkTimestamp:
      type: bigint
      nullable: true
      column: network_timestamp
    lon:
      type: decimal
      nullable: true
    lat:
      type: decimal
      nullable: true
    checkinAddr:
      type: string
      length: 200
      fixed: false
      nullable: true
      column: checkin_addr
    checkinNote:
      type: text
      nullable: true
      column: checkin_note
  lifecycleCallbacks: {  }
