EventLowTemp:
  type: entity
  table: event_low_temp
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    beaconId:
      type: bigint
      nullable: false
      column: beacon_id
    networkTimestamp:
      type: bigint
      nullable: false
      column: network_timestamp
    temperature:
      type: smallint
      nullable: true
    timezone:
      type: float
      nullable: true
    tzAbbrev:
      type: string
      length: 4
      fixed: false
      nullable: true
      column: tz_abbrev
    senId:
      type: bigint
      nullable: true
      column: sen_id
    scenarioName:
      type: string
      length: 100
      fixed: false
      nullable: true
      column: scenario_name
  lifecycleCallbacks: {  }
