EventDetailRpt:
  type: entity
  table: event_detail_rpt
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    scheduledReportId:
      type: bigint
      nullable: true
      column: scheduled_report_id
    dataGroupBy:
      type: string
      length: 10
      fixed: false
      nullable: true
      column: data_group_by
  lifecycleCallbacks: {  }
