IdenCommand:
  type: entity
  table: iden_command
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    beaconId:
      type: bigint
      nullable: false
      column: beacon_id
    ip:
      type: string
      length: 30
      fixed: false
      nullable: true
    command:
      type: string
      length: 100
      fixed: false
      nullable: true
    timestamp:
      type: bigint
      nullable: true
  lifecycleCallbacks: {  }
