InactivityRpt:
  type: entity
  table: inactivity_rpt
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    scheduledReportId:
      type: bigint
      nullable: true
      column: scheduled_report_id
  lifecycleCallbacks: {  }
