Incident:
  type: entity
  table: incident
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    beaconId:
      type: bigint
      nullable: true
      column: beacon_id
    resolutionType:
      type: string
      length: 20
      fixed: false
      nullable: true
      column: resolution_type
    authorityNotified:
      type: string
      length: 20
      fixed: false
      nullable: true
      column: authority_notified
    resolution:
      type: text
      nullable: true
    notes:
      type: text
      nullable: true
    initTimestamp:
      type: bigint
      nullable: false
      column: init_timestamp
    initType:
      type: string
      length: 20
      fixed: false
      nullable: true
      column: init_type
    initAuthentication:
      type: string
      length: 20
      fixed: false
      nullable: true
      column: init_authentication
    status:
      type: string
      length: 20
      fixed: false
      nullable: true
    endTimestamp:
      type: bigint
      nullable: true
      column: end_timestamp
    starttimezone:
      type: float
      nullable: true
    startTzAbbrev:
      type: string
      length: 4
      fixed: false
      nullable: true
      column: start_tz_abbrev
    endtimezone:
      type: float
      nullable: true
    endTzAbbrev:
      type: string
      length: 4
      fixed: false
      nullable: true
      column: end_tz_abbrev
    passcode:
      type: string
      length: 10
      fixed: false
      nullable: false
  oneToOne:
    tracking:
      targetEntity: Tracking
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        tracking_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
