LandmarkCategoryHistory:
  type: entity
  table: landmark_category_history
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    subscriberId:
      type: bigint
      nullable: true
      column: subscriber_id
    organizationId:
      type: bigint
      nullable: true
      column: organization_id
    name:
      type: string
      length: 100
      fixed: false
      nullable: true
    iconId:
      type: bigint
      nullable: true
      column: icon_id
    status:
      type: string
      length: 20
      fixed: false
      nullable: true
    isDefault:
      type: boolean
      nullable: true
      column: is_default
    xid:
      type: bigint
      nullable: true
    isDeleted:
      type: boolean
      nullable: true
      column: is_deleted
    timestamp:
      type: bigint
      nullable: true
    accessListId:
      type: bigint
      nullable: true
      column: access_list_id
  lifecycleCallbacks: {  }
