LoginUg:
  type: entity
  table: login_ug
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    introTs:
      type: bigint
      nullable: false
      column: intro_ts
    retireTs:
      type: bigint
      nullable: false
      column: retire_ts
  oneToOne:
    usergp:
      targetEntity: Usergp
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        usergp_id:
          referencedColumnName: id
      orphanRemoval: false
    login:
      targetEntity: Login
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        login_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
