LojnExpiryNotification:
  type: entity
  table: lojn_expiry_notification
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    beaconServicePlanId:
      type: bigint
      nullable: false
      column: beacon_service_plan_id
    timestamp:
      type: bigint
      nullable: false
    type:
      type: string
      length: 20
      fixed: false
      nullable: true
  lifecycleCallbacks: {  }
