MaintenanceEmailNgHistory:
  type: entity
  table: maintenance_email_ng_history
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    maintenanceId:
      type: bigint
      nullable: true
      column: maintenance_id
    emailId:
      type: bigint
      nullable: true
      column: email_id
    notificationSchemeId:
      type: bigint
      nullable: true
      column: notification_scheme_id
    xid:
      type: bigint
      nullable: true
    isDeleted:
      type: boolean
      nullable: true
      column: is_deleted
    timestamp:
      type: bigint
      nullable: true
    accessListId:
      type: bigint
      nullable: true
      column: access_list_id
  lifecycleCallbacks: {  }
