Make:
  type: entity
  table: make
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    name:
      type: string
      length: 50
      fixed: false
      nullable: true
    version:
      type: string
      length: 20
      fixed: false
      nullable: true
    simRequired:
      type: boolean
      nullable: true
      column: sim_required
  oneToOne:
    manufacturer:
      targetEntity: Manufacturer
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        manufacturer_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
