MdtHistory:
  type: entity
  table: mdt_history
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    assetId:
      type: bigint
      nullable: true
      column: asset_id
    organizationId:
      type: bigint
      nullable: true
      column: organization_id
    customerId:
      type: bigint
      nullable: false
      column: customer_id
    esn:
      type: string
      length: 50
      fixed: false
      nullable: false
    rootPassword:
      type: text
      nullable: true
      column: root_password
    mdtModelId:
      type: bigint
      nullable: false
      column: mdt_model_id
    peripheralStockId:
      type: bigint
      nullable: false
      column: peripheral_stock_id
    xid:
      type: bigint
      nullable: false
    isDeleted:
      type: boolean
      nullable: true
      column: is_deleted
    timestamp:
      type: bigint
      nullable: true
    accessListId:
      type: bigint
      nullable: true
      column: access_list_id
  lifecycleCallbacks: {  }
