MemberHistory:
  type: entity
  table: member_history
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    customerId:
      type: bigint
      nullable: false
      column: customer_id
    daylightSaving:
      type: boolean
      nullable: true
      column: daylight_saving
    username:
      type: string
      length: 20
      fixed: false
      nullable: false
    password:
      type: string
      length: 200
      fixed: false
      nullable: true
    type:
      type: string
      length: 20
      fixed: false
      nullable: true
    firstname:
      type: string
      length: 255
      fixed: false
      nullable: true
    lastname:
      type: string
      length: 255
      fixed: false
      nullable: true
    employeeId:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: employee_id
    phAreacode:
      type: string
      length: 4
      fixed: false
      nullable: true
      column: ph_areacode
    phNumber:
      type: string
      length: 20
      fixed: false
      nullable: true
      column: ph_number
    phExtension:
      type: string
      length: 4
      fixed: false
      nullable: true
      column: ph_extension
    dateDisplayFormat:
      type: string
      length: 20
      fixed: false
      nullable: true
      column: date_display_format
    xid:
      type: bigint
      nullable: false
    isDeleted:
      type: boolean
      nullable: true
      column: is_deleted
    timestamp:
      type: bigint
      nullable: true
    accessListId:
      type: bigint
      nullable: true
      column: access_list_id
    timezone:
      type: float
      nullable: true
  lifecycleCallbacks: {  }
