Module:
  type: entity
  table: module
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    mnemonic:
      type: string
      length: 20
      fixed: false
      nullable: false
    description:
      type: string
      length: 50
      fixed: false
      nullable: false
    introTs:
      type: bigint
      nullable: false
      column: intro_ts
    retireTs:
      type: bigint
      nullable: false
      column: retire_ts
    isVap:
      type: boolean
      nullable: false
      column: is_vap
    isDefault:
      type: boolean
      nullable: false
      column: is_default
    dspOrder:
      type: integer
      unsigned: false
      nullable: true
      column: dsp_order
    propertyKey:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: property_key
  oneToOne:
    permission:
      targetEntity: Permission
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        permission_id:
          referencedColumnName: id
      orphanRemoval: false
    appln:
      targetEntity: Appln
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        appln_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
