NotificationActionHistory:
  type: entity
  table: notification_action_history
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    notificationSchemeId:
      type: bigint
      nullable: true
      column: notification_scheme_id
    actionIndexId:
      type: bigint
      nullable: true
      column: action_index_id
    actionId:
      type: bigint
      nullable: true
      column: action_id
    xid:
      type: bigint
      nullable: false
    isDeleted:
      type: boolean
      nullable: true
      column: is_deleted
    timestamp:
      type: bigint
      nullable: true
    accessListId:
      type: bigint
      nullable: true
      column: access_list_id
  lifecycleCallbacks: {  }
