OrganizationHistory:
  type: entity
  table: organization_history
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    primaryLoginId:
      type: bigint
      nullable: true
      column: primary_login_id
    defaultGuardianId:
      type: bigint
      nullable: true
      column: default_guardian_id
    customerId:
      type: bigint
      nullable: false
      column: customer_id
    status:
      type: string
      length: 20
      fixed: false
      nullable: true
    contactExtention:
      type: string
      length: 10
      fixed: false
      nullable: true
      column: contact_extention
    contactAreacode:
      type: string
      length: 4
      fixed: false
      nullable: true
      column: contact_areacode
    contactEmail:
      type: string
      length: 100
      fixed: false
      nullable: true
      column: contact_email
    name:
      type: string
      length: 255
      fixed: false
      nullable: true
    type:
      type: string
      length: 255
      fixed: false
      nullable: true
    contactName:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: contact_name
    contactNumber:
      type: string
      length: 15
      fixed: false
      nullable: true
      column: contact_number
    streetAddr:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: street_addr
    city:
      type: string
      length: 255
      fixed: false
      nullable: true
    state:
      type: string
      length: 255
      fixed: false
      nullable: true
    country:
      type: string
      length: 255
      fixed: false
      nullable: true
    zipCode:
      type: string
      length: 50
      fixed: false
      nullable: true
      column: zip_code
    bldgNum:
      type: string
      length: 10
      fixed: false
      nullable: true
      column: bldg_num
    timezone:
      type: float
      nullable: true
    daylightSaving:
      type: boolean
      nullable: true
      column: daylight_saving
    csNumber:
      type: string
      length: 20
      fixed: false
      nullable: true
      column: cs_number
    startupTutorial:
      type: boolean
      nullable: true
      column: startup_tutorial
    xid:
      type: bigint
      nullable: false
    isDeleted:
      type: boolean
      nullable: true
      column: is_deleted
    timestamp:
      type: bigint
      nullable: true
    accessListId:
      type: bigint
      nullable: true
      column: access_list_id
    faxAreacode:
      type: string
      length: 4
      fixed: false
      nullable: true
      column: fax_areacode
    faxNumber:
      type: string
      length: 20
      fixed: false
      nullable: true
      column: fax_number
    faxExt:
      type: string
      length: 10
      fixed: false
      nullable: true
      column: fax_ext
    isDeptEnabled:
      type: boolean
      nullable: true
      column: is_dept_enabled
    dexAllowed:
      type: boolean
      nullable: true
      column: dex_allowed
    dexHourQuota:
      type: bigint
      nullable: true
      column: dex_hour_quota
    disclaimerAckTs:
      type: bigint
      nullable: false
      column: disclaimer_ack_ts
    locale:
      type: string
      length: 10
      fixed: false
      nullable: true
    dispatchHourQuota:
      type: bigint
      nullable: true
      column: dispatch_hour_quota
    restServerUrl:
      type: text
      nullable: true
      column: rest_server_url
  lifecycleCallbacks: {  }
