Permission:
  type: entity
  table: permission
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    mnemonic:
      type: string
      length: 40
      fixed: false
      nullable: false
    description:
      type: string
      length: 100
      fixed: false
      nullable: false
    introTs:
      type: bigint
      nullable: false
      column: intro_ts
    retireTs:
      type: bigint
      nullable: false
      column: retire_ts
    dspOrder:
      type: integer
      unsigned: false
      nullable: true
      column: dsp_order
    propertyKey:
      type: string
      length: 255
      fixed: false
      nullable: true
      column: property_key
  oneToOne:
    category:
      targetEntity: PermissionCategory
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        category_id:
          referencedColumnName: id
      orphanRemoval: false
    appln:
      targetEntity: Appln
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        appln_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
