PhoneNotificationGroup:
  type: entity
  table: phone_notification_group
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    notificationSchemeId:
      type: bigint
      nullable: true
      column: notification_scheme_id
    phoneId:
      type: bigint
      nullable: true
      column: phone_id
  lifecycleCallbacks: {  }
