PndDispatcherMsg:
  type: entity
  table: pnd_dispatcher_msg
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    beaconId:
      type: bigint
      nullable: false
      column: beacon_id
    assetId:
      type: bigint
      nullable: false
      column: asset_id
    departmentId:
      type: bigint
      nullable: false
      column: department_id
    pndEsn:
      type: string
      length: 50
      fixed: false
      nullable: false
      column: pnd_esn
    priority:
      type: integer
      unsigned: false
      nullable: true
    message:
      type: text
      nullable: false
    responseType:
      type: string
      length: 50
      fixed: false
      nullable: false
      column: response_type
    status:
      type: string
      length: 50
      fixed: false
      nullable: true
    sentTs:
      type: bigint
      nullable: false
      column: sent_ts
    sentBy:
      type: bigint
      nullable: false
      column: sent_by
    timezone:
      type: float
      nullable: true
    tzAbbrev:
      type: string
      length: 5
      fixed: false
      nullable: true
      column: tz_abbrev
    pndMsgAuditId:
      type: bigint
      nullable: false
      column: pnd_msg_audit_id
    orgPndDispatcherMsgId:
      type: bigint
      nullable: true
      column: org_pnd_dispatcher_msg_id
    pndDispatcherGroupMsgId:
      type: bigint
      nullable: true
      column: pnd_dispatcher_group_msg_id
  lifecycleCallbacks: {  }
