PortmanGt:
  type: entity
  table: portman_gt
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    ip:
      type: string
      length: 30
      fixed: false
      nullable: true
    lastTrackingStopped:
      type: bigint
      nullable: true
      column: last_tracking_stopped
    lastLoginTimestamp:
      type: bigint
      nullable: true
      column: last_login_timestamp
    version:
      type: string
      length: 10
      fixed: false
      nullable: true
  oneToOne:
    beacon:
      targetEntity: Beacon
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        beacon_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
