QuartzNextfire:
  type: entity
  table: quartz_nextfire
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    command:
      type: string
      length: 20
      fixed: false
      nullable: true
    nextFireTimestamp:
      type: bigint
      nullable: true
      column: next_fire_timestamp
  oneToOne:
    sen:
      targetEntity: Sen
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        sen_id:
          referencedColumnName: id
      orphanRemoval: false
    scenario:
      targetEntity: Scenario
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        scenario_id:
          referencedColumnName: id
      orphanRemoval: false
    beacon:
      targetEntity: Beacon
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        beacon_id:
          referencedColumnName: id
      orphanRemoval: false
    actionIndex:
      targetEntity: ActionIndex
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        action_index_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
