ScenarioSvcFeatureHistory:
  type: entity
  table: scenario_svc_feature_history
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    scenarioId:
      type: bigint
      nullable: false
      column: scenario_id
    svcFeatureId:
      type: bigint
      nullable: false
      column: svc_feature_id
    xid:
      type: bigint
      nullable: false
    isDeleted:
      type: boolean
      nullable: true
      column: is_deleted
    timestamp:
      type: bigint
      nullable: false
    accessListId:
      type: bigint
      nullable: true
      column: access_list_id
  lifecycleCallbacks: {  }
