ScheduledReportEmailNg:
  type: entity
  table: scheduled_report_email_ng
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
  oneToOne:
    scheduledReport:
      targetEntity: ScheduledReport
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        scheduled_report_id:
          referencedColumnName: id
      orphanRemoval: false
    notificationScheme:
      targetEntity: NotificationScheme
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        notification_scheme_id:
          referencedColumnName: id
      orphanRemoval: false
    email:
      targetEntity: Email
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        email_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
