ScheduleWeeklyHistory:
  type: entity
  table: schedule_weekly_history
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    scheduleId:
      type: bigint
      nullable: true
      column: schedule_id
    startTimestamp:
      type: bigint
      nullable: true
      column: start_timestamp
    endTimestamp:
      type: bigint
      nullable: true
      column: end_timestamp
    weekdayList:
      type: string
      length: 15
      fixed: false
      nullable: true
      column: weekday_list
    xOccurrences:
      type: smallint
      nullable: true
      column: x_occurrences
    timezone:
      type: float
      nullable: true
    tzAbbrev:
      type: string
      length: 4
      fixed: false
      nullable: true
      column: tz_abbrev
    xid:
      type: bigint
      nullable: false
    isDeleted:
      type: boolean
      nullable: true
      column: is_deleted
    timestamp:
      type: bigint
      nullable: true
    accessListId:
      type: bigint
      nullable: true
      column: access_list_id
  lifecycleCallbacks: {  }
