Sen:
  type: entity
  table: sen
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    name:
      type: string
      length: 100
      fixed: false
      nullable: true
    status:
      type: string
      length: 20
      fixed: false
      nullable: true
    description:
      type: string
      length: 255
      fixed: false
      nullable: true
    trackSequence:
      type: integer
      unsigned: false
      nullable: true
      column: track_sequence
  oneToOne:
    beacon:
      targetEntity: Beacon
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        beacon_id:
          referencedColumnName: id
      orphanRemoval: false
    scenario:
      targetEntity: Scenario
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        scenario_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
