SenHistory:
  type: entity
  table: sen_history
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    name:
      type: string
      length: 100
      fixed: false
      nullable: true
    scenarioId:
      type: bigint
      nullable: true
      column: scenario_id
    beaconId:
      type: bigint
      nullable: true
      column: beacon_id
    status:
      type: string
      length: 20
      fixed: false
      nullable: true
    description:
      type: string
      length: 255
      fixed: false
      nullable: true
    trackSequence:
      type: integer
      unsigned: false
      nullable: true
      column: track_sequence
    xid:
      type: bigint
      nullable: false
    isDeleted:
      type: boolean
      nullable: true
      column: is_deleted
    timestamp:
      type: bigint
      nullable: true
    accessListId:
      type: bigint
      nullable: true
      column: access_list_id
  lifecycleCallbacks: {  }
