SmscFailover:
  type: entity
  table: smsc_failover
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    name:
      type: string
      length: null
      fixed: false
      nullable: true
    ip:
      type: string
      length: 20
      fixed: false
      nullable: false
    port:
      type: integer
      unsigned: false
      nullable: false
    username:
      type: string
      length: 20
      fixed: false
      nullable: false
    password:
      type: string
      length: 20
      fixed: false
      nullable: false
    sysId:
      type: string
      length: 20
      fixed: false
      nullable: false
      column: sys_id
    useTransceiver:
      type: boolean
      nullable: false
      column: use_transceiver
    hostname:
      type: string
      length: null
      fixed: false
      nullable: true
    rUsername:
      type: string
      length: 20
      fixed: false
      nullable: true
      column: r_username
    rPassword:
      type: string
      length: 20
      fixed: false
      nullable: true
      column: r_password
    rSysId:
      type: string
      length: 20
      fixed: false
      nullable: true
      column: r_sys_id
  oneToOne:
    smsc:
      targetEntity: Smsc
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        smsc_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
