Smsc:
  type: entity
  table: smsc
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: SEQUENCE
    name:
      type: string
      length: 20
      fixed: false
      nullable: false
    shortcode:
      type: string
      length: 15
      fixed: false
      nullable: true
    class:
      type: string
      length: null
      fixed: false
      nullable: true
  lifecycleCallbacks: {  }
