SpeedMonitoring:
  type: entity
  table: speed_monitoring
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    speed:
      type: integer
      unsigned: false
      nullable: false
    boundary:
      type: string
      length: 20
      fixed: false
      nullable: true
    gmttimestamp:
      type: bigint
      nullable: true
    isActive:
      type: boolean
      nullable: true
      column: is_active
    speedUnitdisplay:
      type: string
      length: 20
      fixed: false
      nullable: true
      column: speed_unitdisplay
    beginTrapId:
      type: integer
      unsigned: false
      nullable: true
      column: begin_trap_id
    actionId:
      type: bigint
      nullable: true
      column: action_id
  oneToOne:
    beacon:
      targetEntity: Beacon
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        beacon_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
