SrIdleRpt:
  type: entity
  table: sr_idle_rpt
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    scheduledReportId:
      type: bigint
      nullable: true
      column: scheduled_report_id
    idleDuration:
      type: integer
      unsigned: false
      nullable: true
      column: idle_duration
    dataOrderByTime:
      type: string
      length: 5
      fixed: false
      nullable: true
      column: data_order_by_time
    idleDurationUnit:
      type: string
      length: 10
      fixed: false
      nullable: true
      column: idle_duration_unit
  lifecycleCallbacks: {  }
