SrTripRptHistory:
  type: entity
  table: sr_trip_rpt_history
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    scheduledReportId:
      type: bigint
      nullable: true
      column: scheduled_report_id
    tripDuration:
      type: integer
      unsigned: false
      nullable: true
      column: trip_duration
    xid:
      type: bigint
      nullable: true
    isDeleted:
      type: boolean
      nullable: true
      column: is_deleted
    timestamp:
      type: bigint
      nullable: true
    accessListId:
      type: bigint
      nullable: true
      column: access_list_id
    dataOrderByTime:
      type: string
      length: 5
      fixed: false
      nullable: true
      column: data_order_by_time
    tripDurationUnit:
      type: string
      length: 10
      fixed: false
      nullable: true
      column: trip_duration_unit
  lifecycleCallbacks: {  }
