Stepp1:
  type: entity
  table: stepp1
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    shortcode:
      type: string
      length: 30
      fixed: false
      nullable: true
    lastTrackingStopped:
      type: bigint
      nullable: true
      column: last_tracking_stopped
  oneToOne:
    beacon:
      targetEntity: Beacon
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        beacon_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
