SubscriberSolnHistory:
  type: entity
  table: subscriber_soln_history
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    subscriberId:
      type: bigint
      nullable: false
      column: subscriber_id
    solutionId:
      type: bigint
      nullable: false
      column: solution_id
    introTs:
      type: bigint
      nullable: false
      column: intro_ts
    xid:
      type: bigint
      nullable: false
    isDeleted:
      type: boolean
      nullable: true
      column: is_deleted
    timestamp:
      type: bigint
      nullable: false
    accessListId:
      type: bigint
      nullable: true
      column: access_list_id
  lifecycleCallbacks: {  }
