SubscriberModule:
  type: entity
  table: subscriber_module
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    isVisible:
      type: boolean
      nullable: false
      column: is_visible
    isConfigurable:
      type: boolean
      nullable: false
      column: is_configurable
    introTs:
      type: bigint
      nullable: false
      column: intro_ts
  oneToOne:
    subscriber:
      targetEntity: Subscriber
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        subscriber_id:
          referencedColumnName: id
      orphanRemoval: false
    module:
      targetEntity: Module
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        module_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
