TelusService:
  type: entity
  table: telus_service
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    code:
      type: string
      length: 20
      fixed: false
      nullable: false
  lifecycleCallbacks: {  }
