TinyUrl:
  type: entity
  table: tiny_url
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    eventType:
      type: string
      length: 20
      fixed: false
      nullable: false
      column: event_type
    hash:
      type: string
      length: 20
      fixed: false
      nullable: false
    fullUrl:
      type: text
      nullable: false
      column: full_url
    createdTs:
      type: bigint
      nullable: true
      column: created_ts
  lifecycleCallbacks: {  }
