TOrder:
  type: entity
  table: t_order
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    customer:
      type: string
      length: 255
      fixed: false
      nullable: true
  lifecycleCallbacks: {  }
