Tracking:
  type: entity
  table: tracking
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    beaconId:
      type: bigint
      nullable: true
      column: beacon_id
    status:
      type: string
      length: 20
      fixed: false
      nullable: true
    startTimestamp:
      type: bigint
      nullable: false
      column: start_timestamp
    freqSec:
      type: integer
      unsigned: false
      nullable: true
      column: freq_sec
    initialRequestTime:
      type: bigint
      nullable: true
      column: initial_request_time
    endTimestamp:
      type: bigint
      nullable: true
      column: end_timestamp
    starttimezone:
      type: float
      nullable: true
    endtimezone:
      type: float
      nullable: true
  lifecycleCallbacks: {  }
