Trimtrac:
  type: entity
  table: trimtrac
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    beaconId:
      type: bigint
      nullable: false
      column: beacon_id
    issuedCmd:
      type: string
      length: null
      fixed: true
      nullable: true
      column: issued_cmd
    issuedCmdTimestamp:
      type: bigint
      nullable: true
      column: issued_cmd_timestamp
    lastTrackingStopped:
      type: bigint
      nullable: true
      column: last_tracking_stopped
    securityPassword:
      type: string
      length: null
      fixed: true
      nullable: true
      column: security_password
    hpaEnable:
      type: boolean
      nullable: true
      column: hpa_enable
    mpaEnable:
      type: boolean
      nullable: true
      column: mpa_enable
    commMode:
      type: string
      length: null
      fixed: true
      nullable: true
      column: comm_mode
    trackingFreq:
      type: integer
      unsigned: false
      nullable: true
      column: tracking_freq
    motionFreq:
      type: integer
      unsigned: false
      nullable: true
      column: motion_freq
    nonMotionFreq:
      type: integer
      unsigned: false
      nullable: true
      column: non_motion_freq
    scheduledMode:
      type: string
      length: null
      fixed: true
      nullable: true
      column: scheduled_mode
    scheduledTime:
      type: bigint
      nullable: true
      column: scheduled_time
    sequence:
      type: integer
      unsigned: false
      nullable: true
    version:
      type: string
      length: null
      fixed: true
      nullable: true
    unitId:
      type: string
      length: null
      fixed: true
      nullable: true
      column: unit_id
    prevZoneStatus:
      type: bigint
      nullable: true
      column: prev_zone_status
    seqNumber:
      type: integer
      unsigned: false
      nullable: true
      column: seq_number
    lockdown:
      type: boolean
      nullable: true
    motionSensitivity:
      type: string
      length: null
      fixed: true
      nullable: true
      column: motion_sensitivity
    notificationType:
      type: integer
      unsigned: false
      nullable: true
      column: notification_type
  lifecycleCallbacks: {  }
