VapMaintenanceHistory:
  type: entity
  table: vap_maintenance_history
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    vapId:
      type: bigint
      nullable: true
      column: vap_id
    maintenanceId:
      type: bigint
      nullable: true
      column: maintenance_id
    status:
      type: string
      length: 10
      fixed: false
      nullable: true
    initialOdometer:
      type: integer
      unsigned: false
      nullable: true
      column: initial_odometer
    previousStatus:
      type: string
      length: 10
      fixed: false
      nullable: true
      column: previous_status
    lastNotificationTimestamp:
      type: bigint
      nullable: true
      column: last_notification_timestamp
    xid:
      type: bigint
      nullable: true
    isDeleted:
      type: boolean
      nullable: true
      column: is_deleted
    timestamp:
      type: bigint
      nullable: true
    accessListId:
      type: bigint
      nullable: true
      column: access_list_id
  lifecycleCallbacks: {  }
