WebSenHistory:
  type: entity
  table: web_sen_history
  fields:
    id:
      id: true
      type: bigint
      nullable: false
      generator:
        strategy: SEQUENCE
    scenarioId:
      type: bigint
      nullable: true
      column: scenario_id
    itemGroupingId:
      type: bigint
      nullable: true
      column: item_grouping_id
    beaconId:
      type: bigint
      nullable: true
      column: beacon_id
    state:
      type: string
      length: 10
      fixed: false
      nullable: true
    introTs:
      type: bigint
      nullable: true
      column: intro_ts
    retireTs:
      type: bigint
      nullable: true
      column: retire_ts
  lifecycleCallbacks: {  }
