ZoneMonitoringAudit:
  type: entity
  table: zone_monitoring_audit
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: SEQUENCE
    subscriberId:
      type: bigint
      nullable: true
      column: subscriber_id
    organizationId:
      type: bigint
      nullable: true
      column: organization_id
    beaconId:
      type: bigint
      nullable: true
      column: beacon_id
    type:
      type: string
      length: 20
      fixed: false
      nullable: true
    rlat1:
      type: decimal
      nullable: true
    rlat2:
      type: decimal
      nullable: true
    rlon1:
      type: decimal
      nullable: true
    rlon2:
      type: decimal
      nullable: true
    clat:
      type: decimal
      nullable: true
    clon:
      type: decimal
      nullable: true
    cradius:
      type: integer
      unsigned: false
      nullable: true
    boundary:
      type: string
      length: 20
      fixed: false
      nullable: true
    emailNotification:
      type: text
      nullable: true
      column: email_notification
    smsNotification:
      type: text
      nullable: true
      column: sms_notification
    notifyStation:
      type: boolean
      nullable: true
      column: notify_station
    createDate:
      type: bigint
      nullable: true
      column: create_date
    deleteDate:
      type: bigint
      nullable: true
      column: delete_date
    name:
      type: string
      length: 255
      fixed: false
      nullable: true
  lifecycleCallbacks: {  }
