#homepage:
#    pattern:  /
#    defaults: { _controller: ContigoGamPartnerBundle:Default:index }

partner:
    pattern:  /partner/
    defaults: { _controller: ContigoGamPartnerBundle:Default:index }